markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

url: https://shivrm.github.io
permalink: /blog/:title
page_excerpts: true
excerpt_seperator: <!--more-->

collections:
  blog:
    output: true