markdown: kramdown
highlighter: none

kramdown:
  input: GFM
  syntax_highlighter: none

url: https://shivrm.github.io
permalink: /blog/:title
page_excerpts: true
excerpt_seperator: <!--more-->

collections:
  blog:
    output: true